### ISSUE TITLE
AI bros belike "lol I can generate*ARTS* by simply writing prompts" while tryin' hard to mimic the labor done by REAL ARTISTS doing REAL ARTS

### ISSUE THREAD

**Issue by PPAngel345** [lllyasviel/Paints-UNDO#22] opened 2024-07-10 10:35 UTC
Life's good, you AI guys don't need to be so self-abased.

**Comment by yayoyo66** [comment] 2024-07-10 10:55
The ultimate goal of AI research is to pass the Turing test, which is to pretend to be a human, so pretending to be a human artist is the normal way to go

**Comment by PPAngel345** [comment] 2024-07-10 11:02
> The ultimate goal of AI research is to pass the Turing test, which is to pretend to be a human, so pretending to be a human artist is the normal way to go

  Nah from what I'm seeing this is more of a try-hard attempt to impress someone made by somewhat incompetent people than, let's say, a legitimate AI research.

  Hell, even the quote "the ultimate goal is to pass the Turing Test." Sounds like a try-hard attempt to impress Turing himself deep under the grave🪦

**Comment by MangoLion** [comment] 2024-07-10 11:08
Sir, this is a Wendy's

**Comment by PPAngel345** [comment] 2024-07-10 11:10
> Sir, this is a Wendy's

and I'm here for the beef

**Comment by Yosshi999** [comment] 2024-07-10 11:36
duplicate of #2

**Comment by PPAngel345** [comment] 2024-07-10 11:41
> duplicate of #2 
> 

  I'm not discussing about the project's legitimacy, I'm just saying you people should be more confident about yourselves and to not be afraid of accepting your incompetences as they're also a part of who you are.🥰🥰🥰

**Comment by Yosshi999** [comment] 2024-07-10 11:43
> > duplicate of #2
> 
> I'm not discussing about the project's legitimacy, I'm just saying you people should be more confident about yourselves and to not be afraid of accepting your incompetences as they're also a part of who you are.🥰🥰🥰

looks same.

**Comment by PPAngel345** [comment] 2024-07-10 11:45
> > > duplicate of #2
> > 
> > I'm not discussing about the project's legitimacy, I'm just saying you people should be more confident about yourselves and to not be afraid of accepting your incompetences as they're also a part of who you are.🥰🥰🥰
> 
> looks same.
then you should look better, or learn the basics of reading

**Comment by Yosshi999** [comment] 2024-07-10 11:55
anyway only Illya can decide to close it or not. Forget my comment :p

**Comment by sntrenter** [comment] 2024-07-10 13:35
I think installing Gentoo might fix this

**Comment by warwick-davis** [comment] 2024-07-10 13:35
ESL above me

**Comment by anbaphish** [comment] 2024-07-10 13:44
> > duplicate of #2
> 
> I'm not discussing about the project's legitimacy, I'm just saying you people should be more confident about yourselves and to not be afraid of accepting your incompetences as they're also a part of who you are.🥰🥰🥰

I don’t think drawing large amounts of anthropomorphic animals demonstrates competence in the first place. Regardless of thoughts on ml image generation I’d trust someone able to generate decent images locally with any task over 99% of Twitter artists who have to rely on having quarters thrown at them to sustain themselves while they create “art” consisting of incredibly inappropriate subjects that oftentimes border on illegal.

**Comment by Debuggernaut** [comment] 2024-07-10 14:34
> > The ultimate goal of AI research is to pass the Turing test, which is to pretend to be a human, so pretending to be a human artist is the normal way to go
> 
> Nah from what I'm seeing this is more of a try-hard attempt to impress someone made by somewhat incompetent people than, let's say, a legitimate AI research.
> 
> Hell, even the quote "the ultimate goal is to pass the Turing Test." Sounds like a try-hard attempt to impress Turing himself deep under the grave🪦

Get a life, preferably one that doesn't revolve around drawing furry porn

**Comment by PPAngel345** [comment] 2024-07-10 14:55
> > > The ultimate goal of AI research is to pass the Turing test, which is to pretend to be a human, so pretending to be a human artist is the normal way to go
> > 
> > Nah from what I'm seeing this is more of a try-hard attempt to impress someone made by somewhat incompetent people than, let's say, a legitimate AI research.
> > 
> > Hell, even the quote "the ultimate goal is to pass the Turing Test." Sounds like a try-hard attempt to impress Turing himself deep under the grave🪦
> 
> Get a life, preferably one that doesn't revolve around drawing furry porn

I evoked the fear of furry lying down deep inside AI bro's instinct without even mentioning the word "furry" once, this PTSD thing of AI bros is going insane, are you guys ok? Cause you guys should definitely go see a therapist.

**Comment by Yosshi999** [comment] 2024-07-10 15:13
Wait, where did #2 and #3 go? @JapanYoshi you did something?

**Comment by PPAngel345** [comment] 2024-07-10 15:24
> Wait, where did #2 and #3 go? @JapanYoshi you did something?

Probably got reported, that's the open-source and open-minded spirit of AI bros right there, folks.

**Comment by Yosshi999** [comment] 2024-07-10 15:36
> Probably got reported

But the author of #7 remains as ghost. GitHub deleted that user and its entire issues? What is the difference?
Are you familiar with GitHub's Term of Use?

**Comment by PPAngel345** [comment] 2024-07-10 15:38
> > Probably got reported
> 
> But the author of #7 remains as ghost. GitHub deleted that user and its entire issues? What is the difference?
> Are you familiar with GitHub's Term of Use?

Hmm, that's weird......

**Comment by Yosshi999** [comment] 2024-07-10 15:47
I'm afraid that even a 10-years-old user will be erased from Time by a single activity...

**Comment by FieryLionite** [comment] 2024-07-10 16:57
> > Wait, where did #2 and #3 go? @JapanYoshi you did something?
> 
> Probably got reported, that's the open-source and open-minded spirit of AI bros right there, folks.

It's completely reasonable. I'm sure you've heard of the paradox of tolerance? An open-minded group can only remain open-minded and kind if it excludes intolerance and hateful individuals. Bullying and harassment is not welcomed here.

**Comment by Amorano** [comment] 2024-07-10 18:29
> > Wait, where did #2 and #3 go? @JapanYoshi you did something?
> 
> Probably got reported, that's the open-source and open-minded spirit of AI bros right there, folks.

THIS HAS FUCK ALL TO DO WITH ANY ISSUE EXCEPT YOUR PERSONAL ONE.

IT IS REPORTED AN YOU WILL MOST LIKELY BE REMOVED BECAUSE YOU ARE A TROLL.

NOTHING MORE; NOTHING LESS.

**Comment by ARessegetesStery** [comment] 2024-07-10 19:33
Good news - discussions are now closed

So when for the issues? 😂

**Comment by woct0rdho** [comment] 2024-07-10 19:35
At least illya is watching it

**Comment by somespacecowboy** [comment] 2024-07-10 19:36
> Good news - discussions are now closed
> 
> So when for the issues? 😂

lmaoooo as expected! These guys are pretty insecure, aren't they?

**Comment by ARessegetesStery** [comment] 2024-07-10 19:42
@PPAngel345 @Yosshi999 @FieryLionite 
Owner of repo has full right to delete the whole issue on github (instead of only closing them, e.g. in gitea; but admins can do that anyway)

So I guess it probably gets deleted.

**Comment by somespacecowboy** [comment] 2024-07-10 19:46
@ARessegetesStery Oh absolutely, that definitely happened - but I guess the only way forward is to not stop talking about this. I mean, we do keep ratio-ing these guys so that's nice, but staying quiet is the enemy here. Apparently someone told me this was posted on Twitter too so people are going off there too lol.

**Comment by ARessegetesStery** [comment] 2024-07-10 19:48
@somespacecowboy 
Indeed for opposition we need propaganda.

They can control/delete the discussions here, but not on twitter/other social media. I know it has caused heated discussions, at least in Japan.

**Comment by FieryLionite** [comment] 2024-07-10 21:37
> @ARessegetesStery Oh absolutely, that definitely happened - but I guess the only way forward is to not stop talking about this. I mean, we do keep ratio-ing these guys so that's nice, but staying quiet is the enemy here. Apparently someone told me this was posted on Twitter too so people are going off there too lol.

Ah yes, lets keep the heat on and harass, bully another community nonstop so that they'll bend to our will. Oh wait who are the bad guys again??

**Comment by somespacecowboy** [comment] 2024-07-10 21:54
> > @ARessegetesStery Oh absolutely, that definitely happened - but I guess the only way forward is to not stop talking about this. I mean, we do keep ratio-ing these guys so that's nice, but staying quiet is the enemy here. Apparently someone told me this was posted on Twitter too so people are going off there too lol.
> 
> Ah yes, lets keep the heat on and harass, bully another community nonstop so that they'll bend to our will. Oh wait who are the bad guys again??

I don't think anyone believes you're going to change your mind, but speaking out about things you think are wrong or right is a pretty normal thing to do, that's why protests and boycotts exist. People have the right to talk about things they don't like, just as much as you have the right to oppose. I've made it very clear I'm inherently pro-AI, but against the genai usage of datasets without restriction as well as pretending work that was done by a machine was in fact done by yourself. I don't really think it's a hard concept to grasp.

**Comment by lllyasviel** [comment] 2024-07-10 22:35
Hi all, as an action of [GitHub ToS]( https://docs.github.com/en/site-policy/acceptable-use-policies/github-bullying-and-harassment) we must lock this thread. 

For future comments please follow the instructions [here](https://github.com/lllyasviel/Paints-UNDO/issues/41).

**Closed by lllyasviel** 2024-07-10 22:35 UTC
