### ISSUE TITLE
Precisions regarding the training data

### ISSUE THREAD

**Issue by John-WL** [lllyasviel/Paints-UNDO#13] opened 2024-07-10 02:16 UTC
Hello! I'm a big fan of the work you guys do. 

I looked around a little, but I can't find any info about the data that was used to train the models. 
I'm not sure where one can find enough data on the internet for this, and I can't imagine you guys paid real artists for this, because it would simply cost too much money for an open source project. 

Can we have more details about the nature of the dataset?

**Comment by ljleb** [comment] 2024-07-10 02:35
I think this is a duplicate of #4

**Comment by John-WL** [comment] 2024-07-10 02:41
Thank you!

**Closed** 2024-07-10 02:41 UTC
